import * as assert from 'assert'
import { bip39, generateSelfSignedCertificate, hashIdentifier, toMd5, toSha1, toSha256, toSha512 } from '../../lib/crypto'

suite('[Scripts] Crypto', () => {

  suite('Hashing', () => {

    test('Should hash md5', () => {
      const text = `labore dolor adipisicing`
      assert.strictEqual(toMd5(text), `0b64dca35a247169059ed51b0bbdf170`)
    })

    test('Should hash sha1', () => {
      const text = `labore dolor adipisicing`
      assert.strictEqual(toSha1(text), `fedadff71ca0434beef9695b590bb49768988c75`)
    })

    test('Should hash sha256', () => {
      const text = `labore dolor adipisicing`
      assert.strictEqual(toSha256(text), `2bfeca7b44d82aefb3e4c5f7a56fbb93966168891db0955f07436de70ea1a9bd`)
    })

    test('Should hash sha512', () => {
      const text = `labore dolor adipisicing`
      assert.strictEqual(toSha512(text), `34987e192d657ba87de5ad845a003666c6ecb540b2f4fc71a2a650c81eb3a4758d9d95f6d46b83e1e060466b0bf619dabd21732092b787c10cbf4eb066524e6f`)
    })
  })

  test('Should generate bip 39 mnemonic', () => {

    const data = bip39()
    assert.strictEqual(data.mnemonic.split(" ").length, 12)
    assert.strictEqual(data.seed.length, 128)
  })

  test('Should generate self signed certificate', () => {

    // TODO: CHECK DOMAIN IN CERT
    const data = generateSelfSignedCertificate("localhost")
    assert(data.private.includes("-----BEGIN RSA PRIVATE KEY-----"))
    assert(data.cert.includes("-----BEGIN CERTIFICATE-----"))
    assert(data.public.includes("-----BEGIN PUBLIC KEY-----"))
  })


  // Not going into much details as this is generated by another package
  suite('Identify hash algorithm', () => {

    test('md5', () => {

      let hash = "0b64dca35a247169059ed51b0bbdf170"
      let res = hashIdentifier(hash)

      assert(res[0], "MD5")
    })

    test('sha1', () => {

      let hash = "fedadff71ca0434beef9695b590bb49768988c75"
      let res = hashIdentifier(hash)

      assert(res[0], "SHA-1")
    })

    test('sha256', () => {

      let hash = "2bfeca7b44d82aefb3e4c5f7a56fbb93966168891db0955f07436de70ea1a9bd"
      let res = hashIdentifier(hash)

      assert(res[0], "SHA-256")
    })
  })

})
